### ISSUE TITLE
PRNG.md: xoshiro is not newer than xoroshiro

### ISSUE THREAD

**Issue by peteroupc** [bryc/code#4]
The xoroshiro and xoshiro PRNG families were introduced in the same paper, namely "[Scrambled Linear Pseudorandom Number Generators](http://vigna.di.unimi.it/papers.php)" by Blackman and @Vigna, 2019.  Thus, it's almost certainly incorrect to say that the xoshiro family is "newer" than the xoroshiro family or that the latter is "obsolete in favor of" the former.

By the way, the scrambled xorshift family (including xorshift+, etc.) was presented in 2016 under the title "An experimental exploration of Marsaglia's xorshift generators, scrambled" by Vigna.

**Comment by bryc** [comment]
At the time (May 2018), Xoshiro seemed 'new' to me. Xoroshiro128+ had existed since April 2016 although only in source code form and was limited to 64-bit, so I couldn't implement it in JS. The May 2018 paper introduced Xoshiro, as well as additional Xoroshiro variants, including 32-bit versions, so I was happy. It also changed the constants for the original 64-bit Xoroshiro128+.

The reason I said it was "obsolete in favor of": Vigna's page for his PRNGs started off as http://xorshift.di.unimi.it/ in 2014, then http://xoroshiro.di.unimi.it/ (in 2016, proclaiming xoroshiro128+ to be the recommended generator), then http://xoshiro.di.unimi.it/ (immediately putting xoshiro256** at the forefront after the paper's publication in 2018). 

Here are the first revisions of the relevant papers on arXiv.org:

[An experimental exploration of Marsaglia's xorshift generators, scrambled](https://arxiv.org/abs/1402.6246v1), 22 Jan 2014
[Further scramblings of Marsaglia's xorshift generators](https://arxiv.org/abs/1404.0390v1), 1 Apr 2014
[Scrambled Linear Pseudorandom Number Generators](https://arxiv.org/abs/1805.01407v1), 3 May 2018, w/ David Blackman

These are apparently _preprints_, meaning they are not formally peer-reviewed. These papers have various revisions, some being published in journals elsewhere. So it's a bit of a headache. For my purposes I decided the earliest source available was good enough.

**Comment by vigna** [comment]
Historically we worked on them in parallel. They serve different purposes (they fill different points of interest of the state space range) so no one is better in general.
